import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>codesware.com</h1>
      <div className="mx-4 bg-slate-100">hey hello</div>
      <footer > 
      </footer>
    </div>
  )
}
